import type { Metadata } from "next";
import { Chakra_Petch, Inter, Poppins } from "next/font/google";
import "./globals.css";
import BasicLayout from "@/components/Layout/BasicLayout";

const inter = Inter({ subsets: ["latin"] });
const chakra = Chakra_Petch({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BasicLayout>{children}</BasicLayout>
      </body>
    </html>
  );
}
